name: deploy
on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  deploy:
    env:
      platform: linux/amd64,linux/arm64
      # should use a release/version to mark tags
      DOCKER_IMAGE: frozen-shrimp:latest

    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-22.04
    container:
      image: falmar/bitbucket:alpine-3.18
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.platform }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.platform }}
          context: .
          push: true
          file: ./docker/php/Dockerfile
          target: prod
          tags: docker.io/${{ secrets.HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
